# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['service.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'collections',
        'collections.abc',
        'abc',
        'dns',
        'dns.rdtypes',
        'dns.rdtypes.IN',
        'dns.rdtypes.ANY',
        'dns.rdtypes.CH',
        'dns.namedict',
        'dns.resolver',
        'eventlet.hubs',
        'eventlet.hubs.epolls',
        'eventlet.hubs.kqueue',
        'eventlet.hubs.selects',
        'eventlet.hubs.poll',
        'eventlet.hubs.hub',
        'eventlet.hubs.timer',
        'eventlet.green',
        'eventlet.green.select',
        'eventlet.green.threading',
        'eventlet.green.socket',
        'eventlet.green.subprocess',
        'eventlet.green.ssl',
        'eventlet.green.time',
        'eventlet.green.os',
        'eventlet.green.thread',
        'eventlet.greenpool',
        'eventlet.queue',
        'eventlet.timeout',
        'eventlet.websocket',
        'eventlet.wsgi',
        'eventlet.support',
        'eventlet.support.greendns',
        'eventlet.support.psycopg2_patcher',
        'eventlet.support.six',
        'eventlet.support.wrap_threading',
        'greenlet',
        'engineio.async_drivers.eventlet',
        'socketio.async_drivers.eventlet',
        'threading',
        'queue',
        '_thread',
    ],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='service',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='service'
)
